WAV sfx_riff_00 "sfx_riffs/riff_00.wav" XGM
WAV sfx_riff_03 "sfx_riffs/riff_03.wav" XGM
WAV sfx_riff_04 "sfx_riffs/riff_04.wav" XGM
WAV sfx_riff_07 "sfx_riffs/riff_07.wav" XGM
WAV sfx_riff_09 "sfx_riffs/riff_09.wav" XGM
WAV sfx_riff_12 "sfx_riffs/riff_12.wav" XGM
WAV sfx_riff_15 "sfx_riffs/riff_15.wav" XGM
WAV sfx_riff_18 "sfx_riffs/riff_18.wav" XGM
WAV sfx_riff_21 "sfx_riffs/riff_21.wav" XGM
WAV sfx_riff_23 "sfx_riffs/riff_23.wav" XGM
WAV sfx_riff_30 "sfx_riffs/riff_30.wav" XGM
WAV sfx_riff_32 "sfx_riffs/riff_32.wav" XGM
WAV sfx_riff_33 "sfx_riffs/riff_33.wav" XGM
WAV sfx_riff_34 "sfx_riffs/riff_34.wav" XGM
WAV sfx_riff_41 "sfx_riffs/riff_41.wav" XGM
WAV sfx_riff_52 "sfx_riffs/riff_52.wav" XGM
WAV sfx_riff_54 "sfx_riffs/riff_54.wav" XGM
WAV sfx_riff_55 "sfx_riffs/riff_55.wav" XGM
WAV sfx_riff_57 "sfx_riffs/riff_57.wav" XGM
WAV sfx_riff_58 "sfx_riffs/riff_58.wav" XGM
WAV sfx_riff_60 "sfx_riffs/riff_60.wav" XGM
WAV sfx_riff_64 "sfx_riffs/riff_64.wav" XGM
WAV sfx_riff_65 "sfx_riffs/riff_65.wav" XGM
WAV sfx_riff_67 "sfx_riffs/riff_67.wav" XGM
WAV sfx_riff_72 "sfx_riffs/riff_72.wav" XGM
WAV sfx_riff_73 "sfx_riffs/riff_73.wav" XGM
WAV sfx_riff_76 "sfx_riffs/riff_76.wav" XGM
WAV sfx_riff_77 "sfx_riffs/riff_77.wav" XGM
WAV sfx_riff_80 "sfx_riffs/riff_80.wav" XGM
WAV sfx_riff_81 "sfx_riffs/riff_81.wav" XGM
WAV sfx_riff_83 "sfx_riffs/riff_83.wav" XGM
WAV sfx_riff_87 "sfx_riffs/riff_87.wav" XGM
WAV sfx_riff_89 "sfx_riffs/riff_89.wav" XGM
WAV sfx_riff_8A "sfx_riffs/riff_8A.wav" XGM
WAV sfx_riff_91 "sfx_riffs/riff_91.wav" XGM
WAV sfx_riff_92 "sfx_riffs/riff_92.wav" XGM
WAV sfx_riff_97 "sfx_riffs/riff_97.wav" XGM
WAV sfx_riff_9B "sfx_riffs/riff_9B.wav" XGM
WAV sfx_riff_A7 "sfx_riffs/riff_A7.wav" XGM
WAV sfx_riff_B2 "sfx_riffs/riff_B2.wav" XGM